modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Wulian233/Chat-Impressive-Animation/issues"
license = "MIT"

[[mods]]
modId = "chatimpressiveanimation"
version = "${version}"
displayName = "Chat Impressive Animation"
displayURL = "https://github.com/Wulian233/Chat-Impressive-Animation"
authors = "Wulian233, TexTrue"
description = '''
Makes chat messages appear with a smooth animation.
'''
logoFile = "icon.png"

[[mixins]]
config = "chatimpressiveanimation.mixins.json"

[[mixins]]
config = "chatimpressiveanimation.neoforge.mixins.json"

[[dependencies.chatimpressiveanimation]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatimpressiveanimation]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
